### ISSUE TITLE
Embedded STMP incompatible with STMPro

### ISSUE THREAD

**Issue by SoulSin** [mailrelay/magento#1]
Hello.

Well, its rather obvious that the embedded STMP e-mail system that this plugin for magento uses would be incompatible with others extensions of the same kind.

Point is I noticed that even if you set it as "No" to don't use it, it will still cause errors for other SMTP e-mail extensions.

I am using the SMTP Pro by ASchroder. Once MailRelay was installed, despite setting the MailRelay STMP to off, my shop "Form Contact" stopped working entirely and Transactional/Sales e-mails wouldn't arrive at all.

Is there anything that can be done about it?

**Comment by fernandomm** [comment]
We haven't tested our plugin with SMTP Pro. I will try to do some tests, check if I can reproduce this issue and fix it.

**Comment by SoulSin** [comment]
Worth mentioning that I am still using the older version of the SMTP Pro (ver 1.4.3 ), and not the "Ver 2" released on 2014. I don't mind updating it though if found necessary.

My magento version is 1.7.0.2.

I've temporally uninstalled the MailRelay extensions since disabling it on Configuration > Advanced doesn't seens to stop the problem from happening.

Best of luck.

**Comment by fernandomm** [comment]
After doing some tests, I couldn't reproduce this issue. I guess that you may be using an older version of this plugin which had this problem.

Could you try to upgrade the plugin to version 1.2.1 ( http://mailrelay.com/en/plugin/magento-extension )?

**Comment by SoulSin** [comment]
So I will report what I did so far:

With the magento shop working and the plugin uninstalled:
- Installed the plugin
- Checked the e-mail form, wasn't working already (that is before setting up the plugin)
- While Opening Mail Relay Settings at Magento, I got a 404 error. Cleaned the cache and relogged.
- With the Mailrelay settings working properly, i checked if all information and API key were correct. (for some reason, uninstalling the plugin didn't erased that information; Is it stored on the database?)
- Tested the e-mail again. Not working. (Error: Unable to submit your request. Please, try again later)
- Tried disabling SMTP Pro to use "MailRelays" SMTP plugin but due to credential errors (5.8.7) I ended up gaving up. Is the STMP MailRelay Host the same as my hostname?
- Disabled the Mrsynch on the Advanced tab, cleaned cache and relloged.
- Tested e-mail, still not working.
- Unisntalled Mr Sync, cleaned cache, relloged.
- Tried e-mail again, it's working.

Could you tell me which version of the SMTP Pro you used for testing?
I may try updating it another time and test again.

**Comment by fernandomm** [comment]
> Tried disabling SMTP Pro to use "MailRelays" SMTP plugin but due to credential errors (5.8.7) I ended up gaving up. Is the STMP MailRelay Host the same as my hostname?

Yes, it should be the same. Did you send a support request to have your SMTP enabled? It's disabled by default to avoid abuse.

**Comment by elsondinardo** [comment]
Hello, no more updates?
I have this same issue with SMTP... Didn't work properly with Aschroder SMTP.

**Comment by fernandomm** [comment]
Sorry for the delay.

Unfortunately both extensions ( Mailrelay and Aschroder ) override the same class and due to the order in which the classes are loaded ( alphabetical? ), we are the last one to override the core magento class responsible for emails.

I can't provide a solution at this moment, but if you don't want to use our SMTP server you can remove lines 87-91 from the config.xml file manually:

https://github.com/mailrelay/magento/blob/1803bc90622055f3d11e2baa4c210e22c5e04ef8/source/app/code/community/Mailrelay/Mrsync/etc/config.xml#L87

It should stop our extension from overriding Mage_Core_Model_Email_Template, allowing you to use Aschroder's extension.
